In [1]:
from utils import *

dataset = ParkDataset('2022/garage_dataset', len_x=50, in_memory=True)
train_set = dataset[:16000]
test_set = dataset[16000:]

scalar = dataset_scalar(train_set)
train_set.set_scalar(*scalar)
test_set.set_scalar(*scalar)

baseline(test_set, method='mean')
baseline(test_set, method='last')
baseline(test_set, method='yesterday')

loading dataset to memory...


100%|██████████| 33951/33951 [00:10<00:00, 3143.90it/s]


find min max scale...


100%|██████████| 17893/17893 [00:56<00:00, 317.68it/s]


mean
loss_t_1: 0.042821810180971434
loss_t_2: 0.048167781506811364
loss_t_3: 0.053423652283104896
loss_t_avg: 0.0481377479902959
{'ga_mae_15min': 0.10947810770867873, 'ga_mape_15min': 32.48946864695691, 'ga_mae_30min': 0.11793907865039134, 'ga_mape_30min': 33.87155242273515, 'ga_mae_45min': 0.12604664900801663, 'ga_mape_45min': 35.15314298887833}


100%|██████████| 17893/17893 [00:57<00:00, 313.33it/s]


last
loss_t_1: 0.02087522283796336
loss_t_2: 0.026237389378382325
loss_t_3: 0.03260433052044602
loss_t_avg: 0.026572314245597237
{'ga_mae_15min': 0.03760586104849234, 'ga_mape_15min': 11.033660160397922, 'ga_mae_30min': 0.05067641565957381, 'ga_mape_30min': 14.87298978650869, 'ga_mae_45min': 0.06324031569764069, 'ga_mape_45min': 17.90166894875091}


100%|██████████| 17605/17605 [00:57<00:00, 303.63it/s]

loss_t_avg: 0.0836771137215323
None


In [2]:
from utils import *

dataset = ParkDataset('meter_dataset', len_x=50, in_memory=True)
train_set = dataset[:16000]
test_set = dataset[16000:]


baseline(test_set, method='mean')
baseline(test_set, method='last')
baseline(test_set, method='yesterday')

loading dataset to memory...


100%|██████████| 8422/8422 [01:17<00:00, 109.26it/s]


mean
loss_t_1: 0.42812910996956033
loss_t_2: 0.43086442681849074
loss_t_3: 0.43321257916362516
loss_t_avg: 0.43073537198389206
{'me_acc_15min': 0.9043265534233853, 'me_f1_15min': 0.9434127307327461, 'me_acc_30min': 0.8989073558541896, 'me_f1_30min': 0.9402151925569577, 'me_acc_45min': 0.8941683618825834, 'me_f1_45min': 0.9374173068994415}


100%|██████████| 8422/8422 [01:16<00:00, 110.30it/s]


last
loss_t_1: 0.40203818784307
loss_t_2: 0.4109436456309563
loss_t_3: 0.416957384852524
loss_t_avg: 0.4099797394421834
{'me_acc_15min': 0.9441954758001383, 'me_f1_15min': 0.9662692520704294, 'me_acc_30min': 0.9263982169475783, 'me_f1_30min': 0.9556316075561401, 'me_acc_45min': 0.9143866656366603, 'me_f1_45min': 0.9484503656149597}


100%|██████████| 8134/8134 [00:10<00:00, 742.83it/s]

loss_t_avg: 0.4541082099164356
None


In [2]:
from dataset import *

dataset = ParkDataset('garage_dataset', len_x=10, in_memory=True)

loading dataset to memory...


100%|██████████| 24192/24192 [01:12<00:00, 333.55it/s]


In [4]:
dataset[0].x.shape

torch.Size([116, 10])

In [1]:
from utils import *

dataset = CombinedDataset('./')

In [2]:
dataset[0]

HeteroData(
  meter=Data(x=[6225, 10], edge_index=[2, 1470532], y=[6225, 3]),
  garage=Data(x=[121, 10], edge_index=[2, 262], y=[121, 3])
)

In [1]:
[1,2] == [1,2]

True

In [48]:
from utils import *
from torch_geometric.loader import DataLoader
import sklearn.metrics as metrics
import torch
from tqdm import tqdm

dataset = ParkDataset('meter_dataset', len_x=1, len_y=1)

# baseline(dataset[:100], method='1')
y = dataset[-1].x[:, 0]
x = torch.ones_like(y)

metrics.accuracy_score(y, x)

0.0

In [54]:
import os

f = open('problem.txt', 'w')
for i, file in enumerate(tqdm(os.listdir('meter_dataset'))):
    if torch.load('meter_dataset/' + file).sum() == 0:
        f.write(str(file) + '\n')
f.close()

100%|██████████| 44065/44065 [00:12<00:00, 3528.59it/s]


In [16]:
from utils import *
import torch.nn.functional as F
from torch_geometric.nn import SAGEConv, SAGPooling, max_pool_neighbor_x

dataset = ParkDataset('meter_dataset', len_x=10, len_y=3)

data = dataset[0]

conv = SAGEConv(10, 10)
pool = max_pool_neighbor_x


In [19]:
x, edge_index = data.x, data.edge_index
print(data.x[0])
x = conv(x, edge_index)
x.shape

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


torch.Size([6815, 10])

In [18]:
x = pool(x, edge_index)[0]
x.shape

torch.Size([6815, 10])

In [32]:
import torch

loss = torch.nn.BCELoss(reduction='none')

In [33]:
x = dataset[0].x
y = dataset[0].y

loss(x, y).cpu().mean(axis=0).numpy()

array([3.50697  , 3.5216434, 3.3602347], dtype=float32)

In [13]:
from pprint import pprint

a = {1:1, 2:2, 3:3, 4:4, 5:5}
b = {6:6, 7:7, 8:8, 9:9}

f = open('test.txt', 'w')
f.write(str(a))
f.close()

In [10]:
from torch_geometric.loader import DataLoader
loader = DataLoader(dataset, batch_size=3, shuffle=False)

for batch in loader:
    print(batch)
    print(type(batch))
    b1 = batch
    # y = model(batch)
    break

DataBatch(x=[20445, 1], edge_index=[2, 5217477], batch=[20445], ptr=[4])
<class 'torch_geometric.data.batch.DataBatch'>


In [11]:
from torch_geometric.data.collate import collate
from torch_geometric.data import Batch

b2, _, _ = collate(Batch, [dataset[0], dataset[1], dataset[2]])

In [12]:
(b1.x == b2.x).all()

tensor(True)

In [13]:
(b1.edge_index == b2.edge_index).all()

tensor(True)

In [5]:
print(x)
print(y)

DataBatch(x=[20445, 1], edge_index=[2, 5217477], batch=[20445], ptr=[4])
DataBatch(x=[20445, 1], edge_index=[2, 5217477], batch=[20445], ptr=[4])


In [7]:
dataset[0].x.shape[0]

6815

In [50]:
print(y.x.shape)

torch.Size([20445, 1])


In [28]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0],
                           [0]], dtype=torch.long)
x = torch.tensor([[0], [1]], dtype=torch.float)

data_0 = Data(x=x, edge_index=edge_index)

edge_index = torch.tensor([[0],
                           [0]], dtype=torch.long)
x = torch.tensor([[-1]], dtype=torch.float)

data_1 = Data(x=x, edge_index=edge_index)

b, _, _ = collate(Batch, [data_0, data_1])

In [29]:
b.x

tensor([[ 0.],
        [ 1.],
        [-1.]])

In [30]:
b.edge_index

tensor([[0, 2],
        [0, 2]])

In [3]:
import torch
import os.path as osp

xs = []
for i in range(3):
    x = torch.load(osp.join('meter_dataset', f'{i}.pt'))
    xs.append(x)

In [10]:
y = torch.stack(xs, axis=1)

In [12]:
y.shape

torch.Size([6815, 3])